### PR TITLE
Abstract the throttling mechanism

### PR DESCRIPTION
**Pull request by dfithian**
I want to throttle off a different part of the request than the IP. I liked your implementation so I adapted it. As far as I can see, this preserves backwards compatibility. Are you okay with this kind of change?

### CODE REVIEW

**Comment by dfithian** [comment]
@creichert Is this repo still maintained? Thoughts on this PR? I am happy to take it if you don't want it.

**Comment by creichert** [comment]
@dfithian this does look good, love it. I've previously wanted to rate-limit on auth headers and even a few other peices of information.

I do want to merge it. Since you changed a significant portion of it, I added you as a collaborator and we should definitely make sure it's a clean, performant middleware with a low dependency profile.

Thanks!

**Comment by creichert** [comment]
It would be cool to update the README with an example using this new functionality. We'll also need to upload a new version to Hackage.

**Comment by dfithian** [comment]
Absolutely, I will update the README in a new PR.

**Pull request merged**
