### PR TITLE
Use the nightly LTS resolver

### PR DESCRIPTION
**Pull request by dfithian**
Happy to change the resolver to whatever (current is 9.13 I think). Is this what you were suggesting?

### CODE REVIEW

**Comment by creichert** [comment]
Trying to fix CI failures in #14 so we can get this rolling.

**Comment by creichert** [comment]
@dfithian Can you merge the latest master into your branch? It uses a much better CI setup so we can evaluate the builds and make sure there are no problems on the latest nightly.

**Comment by dfithian** [comment]
Looks like it's not working for LTS 2 and 3. Do we need to support those?

**Comment by creichert** [comment]
No, we don't need to. It would be nice to add a few older LTS versions for compatibility reasons (which is why I used pure `cabal-install` before but that's not necessary now).

If you could, though, make the `--resolver latest` an expected failure and remove lts 2 & 3:


I believe the config file just needs this:
```
matrix:
  allow_failures:
    - env: ARGS="--resolver nightly"
```

**Comment by dfithian** [comment]
Okay, locally I have these:
- nightly (can fail)
- 9.13 (no options)
- lts -> defaults to 9.13 for now
- lts-8
- lts-7

The only one that's failing is 7 because of this `checkStatus` -> `checkResponse`. I forget what macro I need to use but I'm looking into it.

**Comment by creichert** [comment]
I believe it would be: `#if MIN_VERSION_wreq(0,5,0)` using `{-# LANGUAGE CPP #-}`.

**Comment by creichert** [comment]
Maybe here: https://github.com/bos/wreq/commit/274b3d543927824161af9871e421a1ef42ae9d98

**Comment by dfithian** [comment]
Ah, perfect. Thanks!

**Comment by dfithian** [comment]
Ugh. [This thread](https://github.com/commercialhaskell/stack/issues/3017) says I should use `-j1`, gonna try with that for lts-7.

**Comment by dfithian** [comment]
@creichert In looking at other open source repositories, I don't see the option `--haddock` used at all. I looked at [persistent](https://github.com/yesodweb/persistent/blob/master/.travis.yml), [esqueleto](https://github.com/bitemyapp/esqueleto/blob/master/.travis.yml), and [lens](https://github.com/ekmett/lens/blob/master/.travis.yml). Is that required?

**Review by creichert — APPROVED** [review]

**Comment by creichert** [comment]
@dfithian Looks great, I'll remove the `--haddock` option. Thanks!

**Pull request merged**
